version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: 'test_farm'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pipeline'
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
